# Debugging LED stim, and doves movie regen
VR March 2026

In [1]:
import retinanalysis as ra

[2026-03-05 15:06:40,067][INFO]: DataJoint 0.14.4 connected to root@127.0.0.1:3306

In [2]:
df = ra.get_datasets_from_protocol_names('ledsawtooth')
df.head()

Found 1 protocols matching "ledsawtooth":
['edu.washington.riekelab.vyom.protocols.LedSawtooth']

Found 8 experiments, 9 epoch blocks.

,exp_name,datafile_name,NDF,chunk_name,protocol_name,is_mea,data_dir,group_label,experiment_id,protocol_id,group_id,block_id,chunk_id
0,20250212C,data019,4.0,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,1,20250212C/data019,LED Sawtooth,114,65,2090,3050,416
1,20250219C,data008,0.0,vyom,edu.washington.riekelab.vyom.protocols.LedSawt...,1,20250219C/data008,sawtooth,115,65,2096,3057,421
2,20250219C,data010,4.0,vyom,edu.washington.riekelab.vyom.protocols.LedSawt...,1,20250219C/data010,sawtooth,115,65,2098,3059,421
3,20250715C,data004,4.0,letters1,edu.washington.riekelab.vyom.protocols.LedSawt...,1,20250715C/data004,VR LED sawtooth,142,65,2398,3574,530
4,20250710C,data015,4.0,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,1,20250710C/data015,VR Sawtooth,143,65,2421,3602,534

In [3]:
i_exp = 1
exp_name = df.loc[i_exp, 'exp_name']
datafile_name = df.loc[i_exp, 'datafile_name']
rb = ra.MEAResponseBlock(exp_name, datafile_name, b_LED=True)

Initializing ResponseBlock for 20250219C block 3057
Loading VCD from /Volumes/Vyom MEA/analysis/20250219C/data008/kilosort2.5 ...
VCD loaded with 602 cells.

In [4]:
sb = ra.MEAStimBlock(exp_name, datafile_name, b_LED=True)

Initializing StimBlock for 20250219C block 3057
Nearest noise chunk for data008 is chunk2 with distance 62 minutes.

In [6]:
rb

MEAResponseBlock with properties:
  exp_name: 20250219C
  datafile_name: data008
  protocol_name: edu.washington.riekelab.vyom.protocols.LedSawtooth
  ss_version: kilosort2.5
  n_epochs: 160
  cell_ids of length: 602
  df_spike_times with times for 602 cells
  block_id: 3057
  d_EIs dictionary containing EIs for 602 cell IDs
  d_timing with keys: ['exp_name', 'block_id', 'epochStarts', 'epochEnds', 'n_samples', 'n_epochs', 'pre_time_ms', 'stim_time_ms', 'tail_time_ms']
  frame_sample_rate: None
  frame_data shape: (0,)

In [5]:
sb

MEAStimBlock with properties:
  exp_name: 20250219C
  block_id: 3057
  prep_label: 20250219Cm1
  datafile_name: data008
  chunk_name: vyom
  protocol_name: edu.washington.riekelab.vyom.protocols.LedSawtooth
  noise_protocol_name: manookinlab.protocols.SpatialNoise
  nearest_noise_chunk: chunk2
  parameter_names of length: 50
  d_epoch_block_params with keys: dict_keys(['amp', 'led', 'preTime', 'stimTime', 'tailTime', 'contrasts', 'sampleRate', 'randomizeOrder', 'numberOfRepeats', 'backgroundIntensity', 'temporalFrequencies'])
  df_epochs for 160 epochs

In [7]:
sb.df_epochs

,epoch_index,currentContrast,currentRapidOnOff,currentUniqueStim,currentFrequency,exp_name,datafile_name,group_label,protocol_name,epoch_parameters,data_dir,preTime,stimTime,tailTime,experiment_id,group_id,block_id,protocol_id,epoch_id
0,0,0.40,0,79.0,78.08,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231017
1,1,0.40,1,14.0,2.44,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231018
2,2,0.20,0,68.0,19.52,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231019
3,3,0.80,1,25.0,9.76,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231020
4,4,0.20,0,43.0,0.61,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,155,0.05,1,36.0,78.08,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231172
156,156,0.80,0,60.0,4.88,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231173
157,157,0.10,0,52.0,2.44,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231174
158,158,0.10,1,27.0,19.52,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231175
159,159,0.10,1,37.0,78.08,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231176