# Debugging LED stim, and doves movie regen
VR March 2026

In [3]:
import retinanalysis as ra

[2026-03-05 15:47:55,377][INFO]: DataJoint 0.14.4 connected to root@127.0.0.1:3306

In [7]:
df = ra.get_datasets_from_protocol_names('ledsawtooth')
df.head()

Found 1 protocols matching "ledsawtooth":
['edu.washington.riekelab.vyom.protocols.LedSawtooth']

Found 8 experiments, 9 epoch blocks.

,exp_name,datafile_name,NDF,chunk_name,protocol_name,is_mea,data_dir,group_label,experiment_id,protocol_id,group_id,block_id,chunk_id
0,20250212C,data019,4.0,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,1,20250212C/data019,LED Sawtooth,114,65,2090,3050,416
1,20250219C,data008,0.0,vyom,edu.washington.riekelab.vyom.protocols.LedSawt...,1,20250219C/data008,sawtooth,115,65,2096,3057,421
2,20250219C,data010,4.0,vyom,edu.washington.riekelab.vyom.protocols.LedSawt...,1,20250219C/data010,sawtooth,115,65,2098,3059,421
3,20250715C,data004,4.0,letters1,edu.washington.riekelab.vyom.protocols.LedSawt...,1,20250715C/data004,VR LED sawtooth,142,65,2398,3574,530
4,20250710C,data015,4.0,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,1,20250710C/data015,VR Sawtooth,143,65,2421,3602,534

In [8]:
i_exp = 1
exp_name = df.loc[i_exp, 'exp_name']
datafile_name = df.loc[i_exp, 'datafile_name']
rb = ra.MEAResponseBlock(exp_name, datafile_name, b_LED=True)

Initializing ResponseBlock for 20250219C block 3057
Loading VCD from /Volumes/Vyom MEA/analysis/20250219C/data008/kilosort2.5 ...
VCD loaded with 602 cells.

In [9]:
sb = ra.MEAStimBlock(exp_name, datafile_name, b_LED=True)

Initializing StimBlock for 20250219C block 3057
Nearest noise chunk for data008 is chunk2 with distance 62 minutes.

In [10]:
rb.vcd.get_ei_for_cell(rb.cell_ids[0])

EIContainer(ei=array([[ 0.18329178,  0.18329178,  0.19409809, ..., -0.49833748,
        -0.46259353, -0.5465503 ],
       [-0.79758936, -0.68287617, -0.6787199 , ...,  0.06359103,
        -0.1957606 , -0.37614298],
       [ 0.18287614,  0.2892768 ,  0.29135495, ..., -0.35785535,
        -0.4023275 , -0.18703242],
       ...,
       [ 0.55444723,  0.64671654,  0.72111386, ..., -0.3088113 ,
        -0.0286783 ,  0.05777224],
       [ 0.3807149 ,  0.15295096, -0.13092269, ..., -0.6147132 ,
        -0.4908562 , -0.37780547],
       [ 0.10598504,  0.17040731, -0.09434746, ..., -0.514547  ,
        -0.55486286, -0.457606  ]], dtype=float32), ei_error=array([[20.036627, 20.167484, 20.044676, ..., 20.635977, 20.58252 ,
        20.163363],
       [28.089842, 28.387657, 28.598772, ..., 26.06475 , 26.326351,
        26.053917],
       [25.59155 , 25.503855, 26.40037 , ..., 24.897537, 25.444727,
        25.811516],
       ...,
       [22.25097 , 21.67488 , 21.188559, ..., 20.491808, 20.43597 ,
        20.859095],
       [19.140697, 18.864897, 18.584663, ..., 18.740559, 18.733301,
        18.816252],
       [19.118565, 18.643171, 18.632727, ..., 18.764864, 18.593369,
        18.881453]], dtype=float32), nl_points=67, nr_points=133, n_samples_total=201)

In [11]:
pl = ra.create_mea_pipeline(exp_name, ['data008', 'data010'], b_LED=True)

Initializing StimBlock for 20250219C block 3057
Nearest noise chunk for data008 is chunk2 with distance 62 minutes.

Initializing StimBlock for 20250219C block 3059
Nearest noise chunk for data010 is chunk2 with distance 4 minutes.

Initializing ResponseBlock for 20250219C block 3057
Loading VCD from /Volumes/Vyom MEA/analysis/20250219C/data008/kilosort2.5 ...
VCD loaded with 602 cells.

Initializing ResponseBlock for 20250219C block 3059
Loading VCD from /Volumes/Vyom MEA/analysis/20250219C/data010/kilosort2.5 ...
VCD loaded with 603 cells.


Generating MEA Response Block from edu.washington.riekelab.vyom.protocols.LedSawtooth datafiles

Lost 1 cells when concatenating response blocks

Generating average EI for all cells
Merged EIs for 602 cells across 2 response blocks
Using chunk2 for AnalysisChunk

Loading VCD from /Volumes/Vyom MEA/analysis/20250219C/chunk2/kilosort2.5 ...
VCD loaded with 564 cells.


Loaded spatial maps for channels [0, 2] and 564 cells of shape (126, 202, 2)
Spatial maps have been padded to align with RF parameters.

Cluster matching 20250219C chunk2 with LedSawtooth ...
72.7% matched, 27.3% unmatched.

Using vr_kilosort2.5.classification.txt for classification.

In [10]:
rb.vcd.get_spike_times_for_cell(rb.cell_ids[0])

array([    1525,     4375,     8548, ..., 27010561, 27020198, 27021203],
      dtype=int32)

In [6]:
rb

MEAResponseBlock with properties:
  exp_name: 20250219C
  datafile_name: data008
  protocol_name: edu.washington.riekelab.vyom.protocols.LedSawtooth
  ss_version: kilosort2.5
  n_epochs: 160
  cell_ids of length: 602
  df_spike_times with times for 602 cells
  block_id: 3057
  d_EIs dictionary containing EIs for 602 cell IDs
  d_timing with keys: ['exp_name', 'block_id', 'epochStarts', 'epochEnds', 'n_samples', 'n_epochs', 'pre_time_ms', 'stim_time_ms', 'tail_time_ms']
  frame_sample_rate: None
  frame_data shape: (0,)

In [5]:
sb

MEAStimBlock with properties:
  exp_name: 20250219C
  block_id: 3057
  prep_label: 20250219Cm1
  datafile_name: data008
  chunk_name: vyom
  protocol_name: edu.washington.riekelab.vyom.protocols.LedSawtooth
  noise_protocol_name: manookinlab.protocols.SpatialNoise
  nearest_noise_chunk: chunk2
  parameter_names of length: 50
  d_epoch_block_params with keys: dict_keys(['amp', 'led', 'preTime', 'stimTime', 'tailTime', 'contrasts', 'sampleRate', 'randomizeOrder', 'numberOfRepeats', 'backgroundIntensity', 'temporalFrequencies'])
  df_epochs for 160 epochs

In [7]:
sb.df_epochs

,epoch_index,currentContrast,currentRapidOnOff,currentUniqueStim,currentFrequency,exp_name,datafile_name,group_label,protocol_name,epoch_parameters,data_dir,preTime,stimTime,tailTime,experiment_id,group_id,block_id,protocol_id,epoch_id
0,0,0.40,0,79.0,78.08,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231017
1,1,0.40,1,14.0,2.44,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231018
2,2,0.20,0,68.0,19.52,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231019
3,3,0.80,1,25.0,9.76,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231020
4,4,0.20,0,43.0,0.61,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,155,0.05,1,36.0,78.08,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231172
156,156,0.80,0,60.0,4.88,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231173
157,157,0.10,0,52.0,2.44,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231174
158,158,0.10,1,27.0,19.52,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231175
159,159,0.10,1,37.0,78.08,20250219C,data008,sawtooth,edu.washington.riekelab.vyom.protocols.LedSawt...,"{'NDF': 0.0, 'amp': 'Amp1', 'led': 'Green LED'...",20250219C/data008,500.0,6000.0,500.0,115,2096,3057,65,231176

## Test with SC

In [ ]:
# ra.populate_database()

Need to convert /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/led_sine_calibration_20250207C.h5 to json
going to implement this eventually
Need to convert /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/20240229C.h5 to json
going to implement this eventually
Need to convert /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/._2024-10-16_E.h5 to json
going to implement this eventually
Need to convert /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/._2025-04-29_E.h5 to json
going to implement this eventually
Need to convert /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/20250306C.h5 to json
going to implement this eventually
Need to convert /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/._2025-08-14_F.h5 to json
going to implement this eventually
Need to convert /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/._2025-08-29_F.h5 to json
going to implement this eventually
Need to convert /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/2025-08-14_F.h5 to json
going to implement this eventually
Need to convert /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/2025-08-29_F.h5 to json
going to implement this eventually
Need to convert /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/._2026-01-02_E_2.h5 to json
going to implement this eventually
Could not find data directory for ._frame_calibration_20250821C.json

Experiments:   0%|          | 0/15 [00:00<?, ?it/s]

Already in database: led_sawtooth_calibrations_20250210C
Already in database: 2024-10-16_E
Already in database: 2025-04-29_E
Already in database: crf_calibrations_20250609C
Already in database: crf_calibrations_20250615C
Already in database: crf_calibrations_20250623C
Already in database: 2025-08-11_dpa_regen
Already in database: 20250814C
Already in database: frame_calibration_20250821C
Already in database: 20250829C
Already in database: 20250917C
Already in database: 20251121_noise_regen
Already in database: noise_test_0921
Already in database: 2026-01-02_E_2
Adding /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/meta/2026-02-24_E_2.json
No new sorting chunks found in database, skipping cell type file population.

In [4]:
exp_name = '2026-02-24_E_2'
df_exp = ra.get_exp_summary(exp_name)

In [5]:
df_exp.query('cell_label=="Cell6"')

,exp_name,prep_label,recording_technique,pipette_solution,cell_id,cell_label,cell_type,NDF,protocol_name,duration_minutes,minutes_since_start,start_time,end_time,cell_properties,group_label,experiment_id,prep_id,group_id,block_id,protocol_id
12,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.protocols.SingleSpot,0.03,102.22,2026-02-24 16:53:29,2026-02-24 16:53:31,{'type': 'horizontal'},Control,186,215,2827,4310,2
13,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.protocols.SingleSpot,0.03,102.42,2026-02-24 16:53:41,2026-02-24 16:53:43,{'type': 'horizontal'},Control,186,215,2827,4311,2
14,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Split...,0.23,103.18,2026-02-24 16:54:15,2026-02-24 16:54:29,{'type': 'horizontal'},Control,186,215,2827,4312,73
15,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Split...,0.25,103.50,2026-02-24 16:54:33,2026-02-24 16:54:48,{'type': 'horizontal'},Control,186,215,2827,4313,73
16,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Split...,0.25,103.82,2026-02-24 16:54:52,2026-02-24 16:55:07,{'type': 'horizontal'},Control,186,215,2827,4314,73
17,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Expan...,0.85,104.83,2026-02-24 16:55:17,2026-02-24 16:56:08,{'type': 'horizontal'},Control,186,215,2827,4315,71
18,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.turner.protocols.Contr...,0.78,105.82,2026-02-24 16:56:20,2026-02-24 16:57:07,{'type': 'horizontal'},Control,186,215,2827,4316,75
19,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,manookinlab.protocols.DovesMovie,1.10,106.98,2026-02-24 16:57:11,2026-02-24 16:58:17,{'type': 'horizontal'},Control,186,215,2827,4317,9
20,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,manookinlab.protocols.DovesMovie,2.18,109.18,2026-02-24 16:58:18,2026-02-24 17:00:29,{'type': 'horizontal'},Control,186,215,2827,4318,9
21,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.rieke.protocols.Variab...,1.68,111.13,2026-02-24 17:00:45,2026-02-24 17:02:26,{'type': 'horizontal'},Control,186,215,2827,4319,91
22,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.rieke.protocols.Variab...,1.68,112.87,2026-02-24 17:02:29,2026-02-24 17:04:10,{'type': 'horizontal'},Control,186,215,2827,4320,91
23,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.protocols.LedNoiseFamily,0.70,113.65,2026-02-24 17:04:15,2026-02-24 17:04:57,{'type': 'horizontal'},Control,186,215,2827,4321,92
24,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.protocols.LedNoiseFamily,0.68,114.37,2026-02-24 17:04:59,2026-02-24 17:05:40,{'type': 'horizontal'},Control,186,215,2827,4322,92
25,2026-02-24_E_2,Preparation,whole-cell,potassium,222,Cell6,horizontal,0.0,edu.washington.riekelab.rieke.protocols.Variab...,1.68,116.08,2026-02-24 17:05:42,2026-02-24 17:07:23,{'type': 'horizontal'},Control,186,215,2827,4323,91

In [7]:
rb = ra.SCResponseBlock(exp_name, 4321, b_LED=True)

Initializing ResponseBlock for 2026-02-24_E_2 block 4321
Loading Amp1 data from /Volumes/Vyom MEA/data/samarjit_datajoint/data_dirs/data/2026-02-24_E_2.h5 ...
Loaded (10, 40000) amp_data.

## Doves stim regen